version: '3.9'

services:
  db:
    image: postgres:17
    container_name: metal_db
    ports:
      - 5432:5432
    volumes:
      - ~/postgresql-metal-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123123
      - POSTGRES_USER=admin
      - POSTGRES_DB=metal_db